rjee_faqs_background_color

rjee_faqs_margin_top
rjee_faqs_margin_bottom
rjee_faqs_margin_left
rjee_faqs_margin_right

rjee_faqs_padding_top
rjee_faqs_padding_bottom
rjee_faqs_padding_left
rjee_faqs_padding_right

rjee_faqs_header_text
rjee_faqs_header_text_font
rjee_faqs_header_text_color
rjee_faqs_header_text_font_size
rjee_faqs_header_align_text

rjee_faqs_header_text_margin_top
rjee_faqs_header_text_margin_bottom
rjee_faqs_header_text_margin_left
rjee_faqs_header_text_margin_right

rjee_faqs_header_text_padding_top
rjee_faqs_header_text_padding_bottom
rjee_faqs_header_text_padding_left
rjee_faqs_header_text_padding_right

accordion_item_margin_top
accordion_item_margin_bottom
accordion_item_margin_left
accordion_item_margin_right

accordion_item_question_background_color
accordion_item_question_background_active_color

accordion_item_question_text_font_size
accordion_item_question_align_text
accordion_item_question_text_font
accordion_item_question_text_color
accordion_item_question_text_active_color

accordion_item_question_border_color
accordion_item_question_border_active_color
accordion_item_question_focus_color


accordion_item_question_border_size
accordion_item_question_border_radius_topleft
accordion_item_question_border_radius_topright
accordion_item_question_border_radius_bottomleft
accordion_item_question_border_radius_bottomright

accordion_item_question_border_radius_after_topleft
accordion_item_question_border_radius_after_topright
accordion_item_question_border_radius_after_bottomleft
accordion_item_question_border_radius_after_bottomright

accordion_item_question_collapse_icon_align
accordion_item_question_non_collapse_icon
accordion_item_question_collapse_icon_font_size
accordion_item_question_collapse_icon_line_height
accordion_item_question_collapse_icon_padding_left
accordion_item_question_collapse_icon_padding_right
accordion_item_question_collapse_icon_padding_top
accordion_item_question_collapse_icon_padding_bottom

